### ISSUE TITLE
Return types give an error

### ISSUE THREAD

**Issue by petrisch** [nushell/tree-sitter-nu#140] opened 2024-11-13 09:39 UTC
In this [project](https://github.com/petrisch/todo-nu) I am trying to use return type annotations.
Which in this minimal case give a error:
```nushell
def foo [
    test: string 
    ] nothing -> string {
         $test
}
foo bla
```
My best guess is, that in this line the return sequence is defined with a colon, which maybe should be a thin_arrow:
https://github.com/nushell/tree-sitter-nu/blob/7e0f16f608a9e804fae61430ade734f9f849fb80/grammar.js#L148

**Comment by blindFS** [comment] 2024-11-13 10:47
It's fixed in this [commit](https://github.com/nushell/tree-sitter-nu/pull/139/commits/989f7ced1d95ec81b2cc088eb395b29b8b48c4a6), but it may take long before merged.

For now, you can add colon before the return type:

```nu
def foo [
    test: string 
    ]: nothing -> string { # <-----
         $test
}
foo bla
```

**Comment by fdncred** [comment] 2024-11-13 12:35
Correct, we might should just close this and not fix it in tree-sitter-nu because improper syntax should show errors, right?
```nushell
def foo [test: string]: nothing -> string { $test }
                      ^
                      |___ Nushell is supposed to require this colon. It is a bug in nushell that an error isn't thrown.
```

**Comment by petrisch** [comment] 2024-11-13 14:03
@fdncred oh there _is_ supposed to be a colon there, gosh I didn't consider that at all.
Makes totally sense, and yes this is not TS-nu's fault then 😄

**Closed** 2024-11-13 14:03 UTC

**Comment by fdncred** [comment] 2024-11-13 14:08
@petrisch right. the problem is that nushell doesn't currently enforce the colon to be there, but it should. that's a bug in nushell.
