### ISSUE TITLE
clang linker command failed

### ISSUE THREAD

**Issue by doongjohn** [nushell/tree-sitter-nu#115] opened 2024-09-24 16:11 UTC
neovim version: v0.10.1
clang version: 19.1.0
OS: Windows 11

```
:TSInstall nu
nvim-treesitter[nu]: Error during compilation
clang: error: linker command failed with exit code 1120 (use -v to see invocation)^M 
```

**Comment by fdncred** [comment] 2024-09-24 16:15
I assume that's because it's not compiling scanner.c. See https://github.com/nushell/tree-sitter-nu/pull/113#issuecomment-2371678047

**Comment by mrdgo** [comment] 2024-09-24 16:17
How do you setup `tree-sitter-nu`?

**Comment by siph** [comment] 2024-09-24 16:36
This broke for me too. I'm using nix to build and install the grammar and now neovim silently crashes whenever I open an `nu` file.

**Comment by fdncred** [comment] 2024-09-24 16:47
I get a silent crash too but it returns `-1073741819` as an exit code.

**Comment by doongjohn** [comment] 2024-09-24 17:58
> How do you setup `tree-sitter-nu`?

I just added `nushell/tree-sitter-nu` as a dependency of `nvim-treesitter/nvim-treesitter` via Lazy nvim.

```lua
  'nvim-treesitter/nvim-treesitter',
  dependencies = {
    'nushell/tree-sitter-nu',
  },
  build = ':TSUpdate',
```

**Comment by doongjohn** [comment] 2024-09-24 18:01
Btw the same config works fine in WSL2 (which has clang 18.1.8).

**Comment by mrdgo** [comment] 2024-09-24 18:12
Ah okay, I can reproduce. It only happens on v0.10.1 - I am on nightly and have no issues.

@fdncred What do you think, we revert until I fixed the problem?

**Comment by fdncred** [comment] 2024-09-24 18:23
Oh, glad you figured out that it's on 0.10.1. Yes, let's revert until we can find a way forward. I just landed the revert. https://github.com/nushell/tree-sitter-nu/pull/116

**Comment by fdncred** [comment] 2024-09-24 18:35
I'm back to normal now. Closing this issue since the revert seems to have fixed it.

**Closed by fdncred** 2024-09-24 18:35 UTC
